apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: managedserviceplans.aerogear.org
spec:
  group: aerogear.org
  names:
    kind: ManagedServicePlan
    listKind: ManagedServicePlanList
    plural: managedserviceplans
    singular: managedserviceplan
  scope: Namespaced
  version: v1alpha1
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            serviceType:
              type: string
            name:
              type: string
            id: 
              type: string
            description:
              type: string
            free:
              type: boolean
            bindParams:
              type: object
            provisionParams:
              type: object