kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: managed-services
rules:
- apiGroups:
  - aerogear.org
  - syndesis.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - namespaces
  - serviceaccounts
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: default-account-managed-services
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: managed-services
  apiGroup: rbac.authorization.k8s.io

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: managed-services
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-cluster-account-managed-services
subjects:
- kind: ServiceAccount
  name: default
  namespace: managed-services-broker
roleRef:
  kind: ClusterRole
  name: managed-services
  apiGroup: rbac.authorization.k8s.io